# Generated by Django 5.1.4 on 2025-01-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godaddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('domain_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='godaddy.domainpuchase')),
            ],
        ),
    ]
