# Generated by Django 5.1.4 on 2025-01-11 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godaddy', '0002_domaindetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedDomainDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_contact_info', models.JSONField()),
                ('updated_status', models.CharField(max_length=50)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('domain_purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='updated_detail', to='godaddy.domainpuchase')),
            ],
        ),
        migrations.DeleteModel(
            name='DomainDetail',
        ),
    ]
