# Generated by Django 5.1.4 on 2025-01-11 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godaddy', '0003_updateddomaindetail_delete_domaindetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateddomaindetail',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='updateddomaindetail',
            name='domain_purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='updated_details', to='godaddy.domainpuchase'),
        ),
    ]
