# Generated by Django 5.1.4 on 2025-01-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godaddy', '0004_remove_updateddomaindetail_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateddomaindetail',
            old_name='updated_contact_info',
            new_name='contact_info',
        ),
        migrations.RemoveField(
            model_name='updateddomaindetail',
            name='domain_purchase',
        ),
        migrations.RemoveField(
            model_name='updateddomaindetail',
            name='updated_status',
        ),
        migrations.AddField(
            model_name='updateddomaindetail',
            name='domain_name',
            field=models.CharField(default='default_domain_name', max_length=255),
        ),
        migrations.AddField(
            model_name='updateddomaindetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
