# Generated by Django 5.1.4 on 2025-01-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('electronic', 'Electronic'), ('grocary', 'Grocary'), ('medicine', 'Medicine'), ('stationary', 'Stationary')], default='electronic', max_length=20)),
            ],
        ),
    ]
