# Generated by Django 5.1.4 on 2025-01-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('merchant', 'Merchant'), ('customer', 'Customer'), ('developer', 'Developer')], default='customer', max_length=20),
        ),
    ]
