# Generated by Django 5.1.4 on 2025-01-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
